"""final

Revision ID: a114c6a65467
Revises: b4fa2e3ea47e
Create Date: 2021-10-28 20:40:51.641067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a114c6a65467'
down_revision = 'b4fa2e3ea47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assessment_description', table_name='assessment')
    op.create_index(op.f('ix_assessment_description'), 'assessment', ['description'], unique=False)
    op.drop_index('ix_assessment_module_code', table_name='assessment')
    op.create_index(op.f('ix_assessment_module_code'), 'assessment', ['module_code'], unique=False)
    op.drop_index('ix_assessment_title', table_name='assessment')
    op.create_index(op.f('ix_assessment_title'), 'assessment', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_title'), table_name='assessment')
    op.create_index('ix_assessment_title', 'assessment', ['title'], unique=False)
    op.drop_index(op.f('ix_assessment_module_code'), table_name='assessment')
    op.create_index('ix_assessment_module_code', 'assessment', ['module_code'], unique=False)
    op.drop_index(op.f('ix_assessment_description'), table_name='assessment')
    op.create_index('ix_assessment_description', 'assessment', ['description'], unique=False)
    # ### end Alembic commands ###
