"""initial migration

Revision ID: b4fa2e3ea47e
Revises: 
Create Date: 2021-10-28 00:06:25.761589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4fa2e3ea47e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('module_code', sa.String(length=10), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_description'), 'assessment', ['description'], unique=True)
    op.create_index(op.f('ix_assessment_module_code'), 'assessment', ['module_code'], unique=True)
    op.create_index(op.f('ix_assessment_title'), 'assessment', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_title'), table_name='assessment')
    op.drop_index(op.f('ix_assessment_module_code'), table_name='assessment')
    op.drop_index(op.f('ix_assessment_description'), table_name='assessment')
    op.drop_table('assessment')
    # ### end Alembic commands ###
